---
# This file contains the configuration for logshipper
#
# inputs[].type: Specifies what kind of parser is used while reading the file
# * syslog: syslog with rfc3339 timestamps
# * clf:    common log format
# * json:   JSON format
#
# inputs[].ts_format: Specify the time format (see golang.org/pkg/time),
#                     defaults are available per input type
# 
amqp:
  name: amqp
  host: rabbitmq.service.as65342
  port: 5672
  username: logshipper
  password:
  exchange: amqp-input

elasticsearch:
  name: es
  host: elasticsearch.service.as65342
  port: 9200
  index: logs

inputs:
  - name: amqp-input
    type: amqpbridge

outputs:
  - name: output to elasticsearch
    type: elasticsearch